name: SimpleCloud-Permission
version: 1.0
author: Wetterbericht

main: eu.thesimplecloud.module.permission.service.spigot.SpigotPluginMain

depend: [ SimpleCloud-Plugin ]

api-version: 1.13

commands:
